services:
  - type: web
    name: compiler-design-lab
    runtime: python
    buildCommand: apt-get update && apt-get install -y graphviz && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: compiler-design-db
          property: connectionString
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: compiler-design-db
    plan: free
